Add home tab
mito-ds/mito pull request #990
Opened 2023-10-26 21:14 UTC by marthacryan

# Description
Moves the existing toolbar into the "Home" tab in preparation for moving the main menu contents into tabs. 

# Testing
Open in a notebook and try out interacting with the tab bar / toolbar buttons! I added a "test" tab so that you can try out switching tabs.

2023-10-26 21:24 UTC, naterush requested changes
Sweet, great start. Minor cleanup, then this is ready to go. 

**Let's not merge this until we get the release out for this week, which I'm working on! But you can branch off of this PR going forward :)**

2023-10-26 21:24 UTC, naterush commented on mitosheet/css/toolbar.css
> +  color: var(--mito-gray);
Can we pick a better color for this? One of the parametric ones.

2023-10-26 21:24 UTC, naterush commented on mitosheet/css/toolbar.css
> +.mito-toolbar-tabbar-button {
rather than overloading button, maybe we rename this to a `tabbar-tabname` (and below).

2023-10-26 21:24 UTC, naterush commented on mitosheet/css/toolbar.css
> +  border-bottom: 3px solid var(--mito-highlight);
In the mockups, we round the corners of these. I think it's a nice bit of polish.

2023-10-26 21:24 UTC, naterush commented on mitosheet/src/mito/components/toolbar/HomeTabContents.tsx
> +        setGridState: React.Dispatch<React.SetStateAction<GridState>>;
setGridState is not used

2023-10-26 21:24 UTC, naterush commented on mitosheet/src/mito/components/toolbar/Toolbar.tsx
> +    const tabs: {[ tab: string ]: React.ReactElement } = {
Can we make `type ToolbarTab = 'Home' | ...` ... and use it where proper?

2023-10-26 21:24 UTC, naterush commented on mitosheet/src/mito/components/toolbar/Toolbar.tsx
> +    const [currentTab, setCurrentTab] = React.useState<string>('Home');
if you make it <ToolbarTab | undefined>, then it's really natural to express the closing operation (it's just undefined)

2023-11-07 22:59 UTC, aarondr77 commented
The unselected tab names look disabled to me, unlike in Excel. 
<img width="339" alt="Screenshot 2023-11-07 at 5 55 53 PM" src="https://github.com/mito-ds/mito/assets/18709905/fc692628-b004-446e-a667-634ae2392f11">

<img width="418" alt="Screenshot 2023-11-07 at 5 57 42 PM" src="https://github.com/mito-ds/mito/assets/18709905/fa89b93c-2aff-4d1d-aa58-b26258212f97">

Can we use the same text color for selectable tab headers as we do for the selectable toolbar buttons?

2023-11-07 23:04 UTC, aarondr77 commented
When you hover over the tab headers, it shifts the placement of the rest of the tab headers because the bold text takes up more width. 

I think an easy fix would be to put each of the sheet tab headers inside a div that has a fixed with so that even if the text width changes the divs don't change sizes

https://github.com/mito-ds/mito/assets/18709905/cf72ea8e-a9fe-4a39-971b-1e34810afe81

2023-11-07 23:09 UTC, aarondr77 commented
Can we update the highlighting so that it as least more closely uniform around the icon. 

In the Import icon, the highlighting pretty much does not exist above icon. You could probably either adjust the icon or find a better padding size? 

<img width="54" alt="Screenshot 2023-11-07 at 5 45 50 PM" src="https://github.com/mito-ds/mito/assets/18709905/b1c346e8-8f1b-4744-9147-b2f5636aee59">

2023-11-07 23:47 UTC, aarondr77 commented
To make it easier to click these buttons, it would be nice if the user could hover over more of the toolbar to select the button. See in the video: 

https://github.com/mito-ds/mito/assets/18709905/cd4f683a-dbcb-4c2f-958e-de8de7e7145c

2023-11-07 23:49 UTC, aarondr77 commented
Can we add tooltips when the elements are disabled that explains these are disabled because you don't have a number column selected. 

<img width="281" alt="Screenshot 2023-11-07 at 6 48 28 PM" src="https://github.com/mito-ds/mito/assets/18709905/9fa81662-9072-4ecc-ae87-4a71a8a63558">

2023-11-07 23:52 UTC, aarondr77 commented
The current implementation of these buttons is reverse from Excel. 

<img width="83" alt="Screenshot 2023-11-07 at 6 52 12 PM" src="https://github.com/mito-ds/mito/assets/18709905/2904ccce-9ade-484c-98b0-681230ebce9b">

2023-11-07 23:54 UTC, aarondr77 commented
The Undo and Redo keyboard shortcuts are broken, but others like Find and Replace are working.

2023-11-07 23:58 UTC, aarondr77 commented
Instead of showing the conditional formatting icon here, I think it's much better for the user if we continue showing the text color and background color that the user sets. 

<img width="425" alt="Screenshot 2023-11-07 at 6 55 50 PM" src="https://github.com/mito-ds/mito/assets/18709905/d4073ef3-3c4c-4035-8211-d51a7d0c1f2a">

Previously, we showed the text color (red) and background color (blue) like this: 
<img width="415" alt="Screenshot 2023-11-07 at 6 57 13 PM" src="https://github.com/mito-ds/mito/assets/18709905/8332d7f0-64de-41b5-a00c-a1083e0efe0d">

2023-11-08 00:03 UTC, aarondr77 commented
You've already called this out, and I agree. The vast majority of adding and deleting events in Mito are on `columns` instead of `rows`. Let's make an icon that looks very similar to these, but is oriented for columns

<img width="94" alt="Screenshot 2023-11-07 at 7 02 04 PM" src="https://github.com/mito-ds/mito/assets/18709905/9b374c07-b587-431d-a78e-72e18910d3dd">

2023-11-08 00:05 UTC, aarondr77 commented
Two updates here:

1. There should be vertical divider bar after the `Delete` icon
2.  In Excel, the order goes `Filter` then `Find and Replace`, so lets go `Filter` `Find and Replace` `Dtype`

<img width="231" alt="Screenshot 2023-11-07 at 7 03 59 PM" src="https://github.com/mito-ds/mito/assets/18709905/13046f34-271b-4456-a7f5-76405f9fced0">

2023-11-08 00:06 UTC, aarondr77 commented
Instead of using this new graph icon in the sheet tab, let's keep the old one. Its a bit overwhelming in the bottom

<img width="97" alt="Screenshot 2023-11-07 at 7 06 21 PM" src="https://github.com/mito-ds/mito/assets/18709905/2d5e9c61-9d0c-4b63-8a1f-fa74395f2b5f">

2023-11-08 00:19 UTC, aarondr77 commented
### Height 

We used to show 13 rows of data, but now we only show 11 because the height of the grid component itself decreased. I think this is not ideal for two reasons: 
1. Being able to see your data is one of our most prominent value props! That's why entering full screen mode is one of the most used features. 
2. There are lots of taskpanes (merge, pivot, graph, etc) that contain a lot of information vertically and already require a lot of scrolling to use. 

Probably as a result of height change and some hardcoding, if you look at the footer, the selected tab and divider line doesn't take up the full height. There's a little bit of cleanup to do here. 
<img width="1058" alt="Screenshot 2023-11-07 at 7 07 22 PM" src="https://github.com/mito-ds/mito/assets/18709905/c5451ce1-36b7-4f11-b132-6e30746e005d">


I think we can win back at least some of the vertical space

This is what we currently have:
<img width="1173" alt="Screenshot 2023-11-07 at 7 18 06 PM" src="https://github.com/mito-ds/mito/assets/18709905/1c4504d5-4879-48c0-b6a3-01a143c31d74">

Just by reducing some of the margins/padding in the toolbar (which I think still looks pretty good) we can get this:
<img width="959" alt="Screenshot 2023-11-07 at 7 17 50 PM" src="https://github.com/mito-ds/mito/assets/18709905/5b9f4483-8d5e-4d5b-ab21-2417ecc29add">

2023-11-08 00:23 UTC, aarondr77 commented
I think these three icons need to be remade. 

1. In the Undo/Redo icons: when you zoom in you can sere the separation between the arrow tip and the arrow body
2. In the clear icon: I don't think we need the black X inside the white X and the right hand side of the icon is cut off. 

<img width="251" alt="Screenshot 2023-11-07 at 7 21 28 PM" src="https://github.com/mito-ds/mito/assets/18709905/ab1e38e4-e411-427c-b507-bb28d30d1c28">

2023-11-08 00:23 UTC, aarondr77 commented
Maybe this icon would look cool if the center of the mirror was black?

<img width="84" alt="Screenshot 2023-11-07 at 7 23 30 PM" src="https://github.com/mito-ds/mito/assets/18709905/7b3e1de8-a184-4ac0-8e75-2b294d48b184">

2023-11-08 00:25 UTC, aarondr77 commented
I know you're already tracking this, but just adding here as well: 

Let's do `pivot` `merge` `graph` `ai`

Where the `merge` is a dropdown button with three options:
1. Horizontal Merge
2. Vertical Concat 
3. Anti Merge

We could probably come up with better names than those too!

<img width="161" alt="Screenshot 2023-11-07 at 7 24 10 PM" src="https://github.com/mito-ds/mito/assets/18709905/6e173980-2caf-4a23-be69-91b2816b8628">

2023-11-08 00:27 UTC, aarondr77 commented
I think we could use a lighter background color for the shading. 

<img width="103" alt="Screenshot 2023-11-07 at 7 26 38 PM" src="https://github.com/mito-ds/mito/assets/18709905/178af517-111a-449c-aded-87a0b442a658">

Something close to this: 
<img width="83" alt="Screenshot 2023-11-07 at 7 27 00 PM" src="https://github.com/mito-ds/mito/assets/18709905/2ec689c8-8acb-49ba-a6be-60500a68e8ec">

2023-11-08 00:28 UTC, aarondr77 commented
These icons have the background included by accident. They should only appear on hover

<img width="142" alt="Screenshot 2023-11-07 at 7 27 38 PM" src="https://github.com/mito-ds/mito/assets/18709905/6cda7fd8-06a9-49bf-99e3-39d0dfecc62b">

2023-11-08 00:32 UTC, aarondr77 commented
I think these icons are a little bit small, especially the lighter `A` are hard to read. Can we make them a tad bigger?

<img width="33" alt="Screenshot 2023-11-07 at 7 31 33 PM" src="https://github.com/mito-ds/mito/assets/18709905/8cfa2860-08ae-4ba4-9f9b-56ff30e7dcee">

2023-11-08 00:33 UTC, aarondr77 commented
This icon is the correct one to use for `Filter and Sort` on the Home tab, but not for the `Filter` icon on the `Data` tab. On the Data tab, it should just have the funnel, not the A Z part

<img width="44" alt="Screenshot 2023-11-07 at 7 32 37 PM" src="https://github.com/mito-ds/mito/assets/18709905/0b1a6d5e-df78-4c0a-b639-dab2e75df73e">

2023-11-08 00:34 UTC, aarondr77 commented
I think these two icons make it seem like these two features are related, when they are not. 

Can we think of a different icon for FillNaN values

<img width="168" alt="Screenshot 2023-11-07 at 7 33 56 PM" src="https://github.com/mito-ds/mito/assets/18709905/61293e4d-3761-4e46-9f35-7b62ef57113a">

2023-11-08 00:37 UTC, aarondr77 commented
Something that just tripped me up was that there isn't an easy way to add a new column when you're writing a formula using this tab. 

<img width="443" alt="Screenshot 2023-11-07 at 7 36 05 PM" src="https://github.com/mito-ds/mito/assets/18709905/e7c9ca23-b25d-40f7-bb9d-b6462c1b45a5">

In Excel, there is an `Insert Function` button here. 
<img width="347" alt="Screenshot 2023-11-07 at 7 37 03 PM" src="https://github.com/mito-ds/mito/assets/18709905/36541c7f-4eca-4cd4-87e7-8b8457c19d7e">

Maybe we could add a button `Insert Column` that creates a new column and opens the cell editor to `=`

2023-11-08 00:38 UTC, aarondr77 commented
I love this checkmark feedback! Nice work

https://github.com/mito-ds/mito/assets/18709905/3511f14a-8ca8-483b-bea2-c5a678162491

2023-11-08 00:41 UTC, aarondr77 commented
The height of the toolbar is slightly different on different tabs. See here that when I switch between the `Formulas` and `Data` tabs the height changes slightly. 

https://github.com/mito-ds/mito/assets/18709905/74984c65-a9b5-4010-82d7-4eecd1bc8bd8

2023-11-08 00:41 UTC, aarondr77 commented
Let's make this text unelectable so this doesn't happen. I think `user-select: none;` will do it. 

<img width="115" alt="Screenshot 2023-11-07 at 7 40 56 PM" src="https://github.com/mito-ds/mito/assets/18709905/5829862d-4a70-4590-b242-991c582eacd3">

2023-11-08 00:48 UTC, aarondr77 commented
If there is a column selected and then you select a function the formula gets entered as `=CLEAN(column_header` but if you just have a cell selected, then the formula is entered as `=CLEAN(`

I think it makes sense to always generate the formula  `=CLEAN(`


https://github.com/mito-ds/mito/assets/18709905/9a24ecd1-f71b-49f3-b09a-e693adbd83f6

2023-11-08 00:49 UTC, aarondr77 commented
The dropdown should be wider to support longer formulas, ie `Start of business month`


<img width="253" alt="Screenshot 2023-11-07 at 7 49 13 PM" src="https://github.com/mito-ds/mito/assets/18709905/6fb35245-91e5-448c-9620-fe4c21975d71">

2023-11-08 00:52 UTC, aarondr77 commented
1. Open a cell editor
2. Use the toolbar to select a formula and see that its added
3. Try to continue typing and notice that the the cell editor no longer has focus in the cell editor. 

I think we should always add the focus to the open cell after we use the formulas toolbar to add a formula

https://github.com/mito-ds/mito/assets/18709905/7185932b-6df9-4ce6-a907-22f5f2b31c97

2023-11-08 01:03 UTC, aarondr77 commented
As much as I love our Mito purple color, I don't love staring at a giant purple bar at the top of the my spreadsheet. I think something like this is much better, and then continuing to use the purple color as an accent. Maybe experiment with a few of the colors we already have in our color scheme and decide which is best? 

<img width="1312" alt="Screenshot 2023-11-07 at 8 01 22 PM" src="https://github.com/mito-ds/mito/assets/18709905/ca99e09f-d4f7-4530-b3ed-983bd8aa16ae">

Hmm... Black is pretty cool too! 
<img width="1199" alt="Screenshot 2023-11-07 at 8 03 17 PM" src="https://github.com/mito-ds/mito/assets/18709905/4bed6ea5-abcc-4469-9748-032eb2c3e831">

2023-11-08 01:07 UTC, aarondr77 commented
Can we add back the `step history` button to the toolbar? I think it could live directly to the left of the `find and replace` and `fullscreen` cluster. It's not the most used feature, but I know that some of our power users really like it.

2023-11-08 01:12 UTC, aarondr77 commented
One hunch I have is that the difference between the `Insert` and `Data` tabs are going to be confusing to users. Let's pay attention to this!

Another structure could be:
1. `Data`: All import, export, change imported data
2. `Transform`:  pivot tables, merge, filter, sort, etc. 

Idk where graphs would go in that grouping though... 

Anyways, I think the tree tests are going to be useful for learning about this! Looking forward to checking them out.

2023-11-08 01:13 UTC, aarondr77 commented
Ooooo I would be down to add the text `Auto Save` in the top toolbar. One question I often get is, "Is this saving automatically?" 

Excel has it here. We could add the text "Auto Save" (without the ability to turn it off), and then a tooltip that gives a little bit more context when you hover over it. 

<img width="531" alt="Screenshot 2023-11-07 at 8 13 13 PM" src="https://github.com/mito-ds/mito/assets/18709905/8f95537d-a952-4292-b26e-746263874929">

2023-11-08 14:43 UTC, aarondr77 commented
Noticed this bug while testing. https://github.com/mito-ds/mito/issues/1018 However, its probably not related to this PR, right?

2023-11-09 03:41 UTC, marthacryan commented
> Can we add tooltips when the elements are disabled that explains these are disabled because you don't have a number column selected.

I think there is? Are there specific buttons that aren't saying that?

2023-11-10 00:53 UTC, marthacryan commented
> Maybe this icon would look cool if the center of the mirror was black?
> 
> <img alt="Screenshot 2023-11-07 at 7 23 30 PM" width="84" src="https://user-images.githubusercontent.com/18709905/281219062-7b3e1de8-a184-4ac0-8e75-2b294d48b184.png">

I might just remove the fill altogether?

2023-11-10 02:10 UTC, marthacryan commented
> You've already called this out, and I agree. The vast majority of adding and deleting events in Mito are on `columns` instead of `rows`. Let's make an icon that looks very similar to these, but is oriented for columns
> 
> <img alt="Screenshot 2023-11-07 at 7 02 04 PM" width="94" src="https://user-images.githubusercontent.com/18709905/281216049-9b374c07-b587-431d-a78e-72e18910d3dd.png">

How does this look? 
<img width="444" alt="image" src="https://github.com/mito-ds/mito/assets/6673460/bde9a21b-b924-4b60-83ca-c069c8bac8c0">

2023-11-10 02:13 UTC, marthacryan commented
> As much as I love our Mito purple color, I don't love staring at a giant purple bar at the top of the my spreadsheet. I think something like this is much better, and then continuing to use the purple color as an accent. Maybe experiment with a few of the colors we already have in our color scheme and decide which is best?

I agree that the 

> This icon is the correct one to use for `Filter and Sort` on the Home tab, but not for the `Filter` icon on the `Data` tab. On the Data tab, it should just have the funnel, not the A Z part
> 
> <img alt="Screenshot 2023-11-07 at 7 32 37 PM" width="44" src="https://user-images.githubusercontent.com/18709905/281220208-0b1a6d5e-df78-4c0a-b639-dab2e75df73e.png">

To be clear though, these two buttons are doing the same thing. Should they be doing something different?

2023-11-10 16:33 UTC, merged

2023-11-13 21:41 UTC, marthacryan commented
> Probably as a result of height change and some hardcoding, if you look at the footer, the selected tab and divider line doesn't take up the full height. Neither does the graph tabs. There's a little bit of cleanup to do here. <img alt="Screenshot 2023-11-07 at 7 07 22 PM" width="1058" src="https://user-images.githubusercontent.com/18709905/281216978-c5451ce1-36b7-4f11-b132-6e30746e005d.png">

I'm not able to reproduce this - what browser are you in? Are you in JL or streamlit?